maintainers:
 - alexellis
 
features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes

custom_messages:
  - name: slack
    value: |
           --
           Join Slack to connect with the community using the `#inlets` channel
           within the OpenFaaS Slack workspace.
           https://docs.openfaas.com/community

